name: 🐞 Bug Report
description: Report a bug or issue
title: "[BUG]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain the issue.
    validations:
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
      multiple: true
      description: Select the browser where the issue occurred.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We'll look into it as soon as possible.